#coding=utf-8
# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www.gnu.org/licenses/>.

# frameworks/base/core/res/AndroidManifest.xml
########################################## PERMISSIONS ########################################################
DVM_PERMISSIONS = {
    "MANIFEST_PERMISSION" : {
	"SEND_SMS": ["dangerous",u"发送短信",u"允许应用发送短信"],
	"SEND_SMS_NO_CONFIRMATION" : ["dangerous",u"无提示发送短信",u"允许应用无需用户确认就能发送短信"],
    "RECEIVE_SMS": ["dangerous",u"接收短信",u"允许应用可监控短信接收"],
	"CALL_PHONE" : [ "normal" , u"拨打电话" , u"允许应用拨打电话"],
    "CALL_PRIVILEGED": ["dangerous",u"无提示拨打电话",u"允许应用可无提示直接拨打电话"],
    "INTERNET": ["normal",u"访问网络",u"允许应用具有完全的互联网访问权限"],
    "READ_CONTACTS": ["dangerous",u"读取联系人信息",u"允许应用可读取联系人信息"],
    "WRITE_CONTACTS": ["dangerous",u"写联系人信息",u"允许应用可修改联系人信息"],
    "CHANGE_WIFI_STATE": ["dangerous",u"修改wifi状态",u"允许应用可修改设备当前WIFI设置"],
    "WRITE_EXTERNAL_STORAGE": ["dangerous",u"读写外部存储",u"允许应用可对外部存储卡进行读写操作"],
    "INSTALL_SHORTCUT": ["dangerous",u"创建快捷方式",u"允许应用可创建程序快捷方式"],
    "READ_PHONE_STATE": ["dangerous",u"读取设备状态信息",u"允许应用可读取设备状态信息"],
    "INSTALL_PACKAGES": ["dangerous",u"安装应用",u"允许应用可安装其它应用"],
    "READ_SMS": ["dangerous",u"读取信息",u"允许应用读取短信或彩信"],
    "WRITE_SMS": ["dangerous",u"编辑信息",u"允许应用编辑短信或彩信"],
    "RESTART_PACKAGES": ["dangerous",u"重启应用程序",u"允许应用重启应用程序"],
    "ACCESS_COARSE_LOCATION": ["dangerous",u"获取粗略位置信息",u"允许应用可获取当前粗略位置信息"],
    "ACCESS_FINE_LOCATION": ["dangerous",u"获取设备精确位置",u"允许应用可获取当前精确位置信息"],
    "ACCESS_CHECKIN_PROPERTIES": ["dangerous",u"访问checkin数据库中properites表信息",u"允许应用读写访问”properties”表在checkin数据库中，改值可以修改上传"],
    "ACCESS_LOCATION_EXTRA_COMMANDS": ["dangerous",u"访问额外位置提供命令",u"允许应用程序访问额外的位置提供命令"],
    "ACCESS_MOCK_LOCATION": ["dangerous",u"创建模拟位置",u"允许程序创建模拟位置提供用于测试"],
    "ACCESS_NETWORK_STATE": ["dangerous",u"访问GSM网络信息",u"允许程序访问有关GSM网络信息"],
    "ACCESS_SURFACE_FLINGER": ["dangerous",u"访问urfaceFlinger信息",u"允许程序使用SurfaceFlinger底层特性"],
    "ACCESS_WIFI_STATE": ["dangerous",u"获取wifi状态",u"允许程序访问Wi-Fi网络状态信息"],
    "ADD_SYSTEM_SERVICE": ["dangerous",u"添加系统服务",u"允许程序发布系统级服务"],
    "BATTERY_STATS": ["dangerous",u"访问电池统计信息",u"允许程序更新设备电池统计信息"],
    "BLUETOOTH": ["dangerous",u"蓝牙连接",u"允许程序连接到已配对的蓝牙设备"],
    "BLUETOOTH_ADMIN": ["dangerous",u"管理蓝牙设备",u"允许程序发现和配对蓝牙设备"],
    "BRICK": ["dangerous",u"禁用设备",u"请求能够禁用设备"],
    "BROADCAST_PACKAGE_REMOVED": ["dangerous",u"广播程序移除信息",u"允许程序广播一个提示消息在一个应用程序包已经移除后"],
    "BROADCAST_STICKY": ["dangerous",u"广播常用intents",u"允许一个程序广播常用intents"],
    "CAMERA": ["dangerous",u"访问相机",u"请求访问使用照相设备"],
    "CHANGE_COMPONENT_ENABLED_STATE": ["dangerous",u"改变组件状态",u"允许一个程序是否改变一个组件或其他的启用或禁用"],
    "CHANGE_CONFIGURATION": ["dangerous",u"修改配置文件",u"允许一个程序修改当前设置，如本地化"],
    "CHANGE_NETWORK_STATE": ["dangerous",u"修改网络状态",u"允许程序改变网络连接状态"],
    "CLEAR_APP_CACHE": ["dangerous",u"清除应用缓存",u"允许一个程序清楚缓存从所有安装的程序在设备中"],
    "CLEAR_APP_USER_DATA": ["dangerous",u"清除用户设置",u"允许一个程序清除用户设置"],
    "CONTROL_LOCATION_UPDATES": ["dangerous",u"控制位置更新",u"允许启用禁止位置更新提示从无线模块"],
    "DELETE_CACHE_FILES": ["dangerous",u"删除缓存文件",u"允许程序删除缓存文件"],
    "DELETE_PACKAGES": ["dangerous",u"删除包",u"允许一个程序删除包"],
    "DEVICE_POWER": ["dangerous",u"访问底层电池管理",u"允许程序访问底层电源管理"],
    "DIAGNOSTIC": ["dangerous",u"访问诊断资源",u"允许程序RW诊断资源"],
    "DISABLE_KEYGUARD": ["dangerous",u"禁用键盘",u"允许程序禁用键盘锁"],
    "DUMP": ["dangerous",u"转存信息",u"允许程序从系统服务返回状态抓取信息"],
    "EXPAND_STATUS_BAR": ["dangerous",u"扩展状态栏",u"允许一个程序扩展收缩在状态栏,android开发网提示应该是一个类似windows mobile中的托盘程序"],
    "FACTORY_TEST": ["dangerous",u"工厂测试程序",u"作为一个工厂测试程序，运行在root用户"],
    "FLASHLIGHT": ["normal",u"访问闪光灯",u"访问闪光灯,android开发网提示htc Dream不包含闪光灯"],
    "FORCE_BACK": ["dangerous",u"强制执行后退操作",u"允许程序强制执行一个后退操作检测是否在顶层activities"],
    "GET_ACCOUNTS": ["dangerous",u"获取账户",u"访问Accounts Service帐户列表中的一个账户"],
    "GET_PACKAGE_SIZE": ["dangerous",u"获取包大小",u"允许一个程序获取任何package占用空间容量"],
    "GET_TASKS": ["dangerous",u"获取任务列表",u"允许一个程序获取信息有关当前或最近运行的任务，一个缩略的任务状态，是否活动等等"],
    "HARDWARE_TEST": ["dangerous",u"测试硬件",u"允许测试硬件"],
    "INJECT_EVENTS": ["dangerous",u"事件注入",u"允许一个程序截获用户事件如按键、触摸、轨迹球等等到一个时间流"],
    "INTERNAL_SYSTEM_WINDOW": ["dangerous",u"内部系统界面",u"允许打开窗口使用系统用户界面"],
    "MANAGE_APP_TOKENS": ["dangerous",u"管理应用tokens",u"允许应用管理其他应用的tokens"],
    "MASTER_CLEAR ": ["dangerous",u"清理数据",u"允许应用清除一切数据"],
    "MODIFY_AUDIO_SETTINGS": ["dangerous",u"修改音频设置",u"允许程序修改全局音频设置"],
    "MODIFY_PHONE_STATE": ["dangerous",u"修改设备状态",u"允许修改话机状态，如电源，人机接口等"],
    "MOUNT_UNMOUNT_FILESYSTEMS": ["dangerous",u"挂载/卸载filesystem分区",u"允许挂载和反挂载文件系统可移动存储"],
    "PERSISTENT_ACTIVITY": ["dangerous",u"持久活动",u"允许一个程序设置他的activities为持久活动"],
    "PROCESS_OUTGOING_CALLS": ["dangerous",u"监控播出电话",u"允许程序监视、修改有关播出电话"],
    "READ_CALENDAR": ["dangerous",u"读取日历信息",u"允许程序读取用户日历数据"],
    "READ_FRAME_BUFFER": ["dangerous",u"读取帧缓存",u"允许程序屏幕波或和更多常规的访问帧缓冲数据"],
    "READ_INPUT_STATE": ["dangerous",u"读取输入状态",u"允许程序返回当前按键状态"],
    "READ_LOGS": ["dangerous",u"读取日志信息",u"允许程序读取底层系统日志文件"],
    "READ_OWNER_DATA": ["dangerous",u"读取所有者数据",u"允许程序读取所有者数据"],
    "READ_SYNC_SETTINGS": ["dangerous",u"读取同步设置",u"允许程序读取同步设置"],
    "READ_SYNC_STATS": ["dangerous",u"读取同步状态",u"允许程序读取同步状态"],
    "REBOOT": ["dangerous",u"重启设备",u"请求能够重新启动设备"],
    "RECEIVE_BOOT_COMPLETED": ["dangerous",u"获取启动完成信息",u"允许一个程序接收到 ACTION_BOOT_COMPLETED广播在系统完成启动"],
    "RECEIVE_MMS": ["dangerous",u"接收MMS信息",u"允许一个程序监控将收到MMS彩信,记录或处理"],
    "RECEIVE_WAP_PUSH": ["dangerous",u"接收WAP推送",u"允许程序监控将收到WAP PUSH信息"],
    "RECORD_AUDIO": ["dangerous",u"录音",u"允许程序录制音频"],
    "REORDER_TASKS": ["dangerous",u"修改任务列表",u"允许程序改变Z轴排列任务"],
    "SET_ACTIVITY_WATCHER": ["dangerous",u"设置活动监控",u"允许程序监控或控制activities"],
    "SET_ALWAYS_FINISH": ["dangerous",u"设置总是完成",u"允许程序控制活动在处于后台时是否间接完成"],
    "SET_ANIMATION_SCALE": ["dangerous",u"设置提示范围",u"修改全局提示信息比例"],
    "SET_DEBUG_APP": ["dangerous",u"设置调试",u"配置一个程序用于调试"],
    "SET_ORIENTATION": ["dangerous",u"设置方向",u"允许底层访问设置屏幕方向和实际旋转"],
    "SET_PREFERRED_APPLICATIONS": ["dangerous",u"设置应用配置",u"允许一个程序修改列表参数PackageManager.addPackageToPreferred 和PackageManager.removePackageFromPreferred方法"],
    "SET_PROCESS_FOREGROUND": ["dangerous",u"设置程序为前台执行",u"允许程序当前运行程序强行到前台"],
    "SET_PROCESS_LIMIT": ["dangerous",u"设置最大程序个数限制",u"允许设置最大的运行进程数量"],
    "SET_TIME_ZONE": ["dangerous",u"设置时区",u"允许程序设置时间区域"],
    "SET_WALLPAPER": ["dangerous",u"设置壁纸",u"允许程序设置壁纸"],
    "SET_WALLPAPER_HINTS": ["dangerous",u"设置壁纸hits",u"允许程序设置壁纸hits"],
    "SIGNAL_PERSISTENT_PROCESSES": ["dangerous",u"发送程序信号",u"允许程序请求发送信号到所有显示的进程中"],
    "STATUS_BAR": ["dangerous",u"访问状态栏",u"允许程序打开、关闭或禁用状态栏及图标"],
    "SUBSCRIBED_FEEDS_READ": ["dangerous",u"访问RSS Feed内容",u"允许一个程序访问订阅RSS Feed内容提供"],
    "SUBSCRIBED_FEEDS_WRITE": ["dangerous",u"写RSS Feed内容",u"系统暂时保留改设置,android开发网认为未来版本会加入该功能"],
    "SYSTEM_ALERT_WINDOW": ["dangerous",u"设置系统提示窗口",u"允许一个程序打开窗口使用 TYPE_SYSTEM_ALERT，显示在其他所有程序的顶层"],
    "VIBRATE": ["dangerous",u"震动设备",u"允许访问振动设备"],
    "WAKE_LOCK": ["dangerous",u"设置wakelocks显示状态",u"允许使用PowerManager的 WakeLocks保持进程在休眠时从屏幕消失"],
    "WRITE_APN_SETTINGS": ["dangerous",u"写APN设置",u"允许程序写入API设置"],
    "WRITE_CALENDAR": ["dangerous",u"写日历信息",u"允许一个程序写入但不读取用户日历数据"],
    "WRITE_GSERVICES": ["dangerous",u"修改google服务",u"允许程序修改Google服务"],
    "WRITE_OWNER_DATA": ["dangerous",u"写入程序所有者的信息",u"允许一个程序写入但不读取所有者数据"],
    "WRITE_SETTINGS": ["dangerous",u"写入系统设置",u"允许程序写入系统设置"],
    "READ_SETTINGS": ["dangerous",u"读取系统设置",u"允许程序读取系统设置"],
    "WRITE_SYNC_SETTINGS":["dangerous",u"写入同步设置",u"允许程序写入同步设置"],
    "UNINSTALL_SHORTCUT":["dangerous", u"卸载快捷方式",u"允许程序卸载快捷启动图案"],
    "USE_CREDENTIALS":["dangerous", u"使用证书",u"允许程序使用证书"],
    "CREATE_SHORTCUT":["signature", u"安装快捷启动方式", u"允许程序安装快捷启动方式"],
    "ADD_VOICEMAIL" : [ "dangerous", u"添加语音邮件到系统", u"允许应用添加语音邮件到系统" ],
    "ACCESS_GPS": ["normal",u"访问GPS获取位置信息",u"允许应用访问GPS获取位置信息"],
    "DOWNLOAD_WITHOUT_NOTIFICATION" : ["dangerous", u"不通知用户直接下载", u"允许应用不通知用户而直接下载"],
    "READ_EXTERNAL_STORAGE" : ["normal", u"访问外置存储", u"允许应用访问外置存储"],
    "ACCESS_DOWNLOAD_MANAGER" : ["dangerous", u"访问下载管理器", u"允许应用访问下载管理器"],
    "BAIDU_LOCATION_SERVICE" : ["normal", u"百度位置服务", u"允许应用通过百度位置服务获取当前位置"],
    "KILL_BACKGROUND_PROCESSES": ["dangerous", u"终止后台进程", u"允许应用终止后台进程"],
    "DOWNLOAD_NOTIFICATION_CLICKED":["normal", u"点击下载通知", u"允许应用在通知栏点击下载通知信息"],
    "MANAGE_ACCOUNTS":["dangerous", u"管理账户", u"允许应用程序管理账户"],
    "ACCESS_SUPERUSER" : ['dangerous', u"访问root用户", u"允许用户使用root权限"],
    "BILLING" : ['dangerous', u"应用内支付", u"允许应用内支付"],
    },

    "MANIFEST_PERMISSION_GROUP" : 
        {

        "ACCOUNTS" : u"通过Accout Manager直接访问accounts管理的权限.",
        "COST_MONEY" : u"花费用户资金而不需要用户直接参与的权限.",
        "DEVELOPMENT_TOOLS" : u"与开发向相关的组权限.",
        "HARDWARE_CONTROLS" : u"控制硬件设备的权限.",
        "LOCATION" : u"获取用户当前位置的权限.",
        "MESSAGES" : u"允许应用程序代表用户发送消息或拦截被用户接受的消息的权限.",
        "NETWORK" : u"访问网络的权限.",
        "PERSONAL_INFO" : u"访问用户私人信息,如联系人、日历信息、e-mail信息等的权限.",
        "PHONE_CALLS" : u"访问和修改电话状态:比如拦截即将拨出的电话,读取和修改手机的状态等的权限.",
        "STORAGE" : u"访问SD card的权限.",
        "SYSTEM_TOOLS" : u"系统相关API.",
    },
}
